#!/bin/sh

cd ~/Downloads
wget ftp://ftp.perforce.com/perforce/r17.1/bin.linux26x86_64/p4d
chmod +x p4d
sudo mv p4d ~/Workspace/Binaries
paket install daemon
sudo mkdir -p $HOME/Workspace/Perforce
sudo adduser perforce
sudo chown perforce $HOME/Workspace/Perforce
sudo mkdir /var/log/perforce
sudo chown perforce /var/log/perforce
#wget https://raw.githubusercontent.com/BlurryRoots/linux-perforce-installer/master/p4dservice
chmod +x p4dservice
ln -s p4dservice /etc/init.d/p4dservice
sudo update-rc.d p4dservice defaults
sudo reboot